[build]
  command = "curl -sL https://github.com/gohugoio/hugo/releases/download/v0.142.0/hugo_0.142.0_Linux-64bit.tar.gz | tar -xz && ./hugo --gc --themesDir ./themes/"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.142.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
  HUGO_EXTENDED = "true"
